### ISSUE TITLE
[EDH-2277] Duplicate Agreement Admin sections in Swagger

### ISSUE THREAD

**Issue by EinarArro** [Elering/estfeed-datahub-docs#10]
![CleanShot 2024-04-15 at 10 13 22@2x](https://github.com/Elering/estfeed-datahub-docs/assets/2980916/dc88e243-28dc-4966-9aed-d9d1896f237f)

**Comment by mailimarkvardt** [comment]
OK also in public test: 
![image](https://github.com/Elering/estfeed-datahub-docs/assets/173887389/40976478-9c83-45f9-839c-0d1c36568bce)
