### ISSUE TITLE
Joint billing contracts that lasted only 1 day

### ISSUE THREAD

**Issue by DenEnefit** [Elering/estfeed-datahub-docs#105]
In old AVP solution these contracts worked. In new Estfeed solution they get rejected.

One day contracts should be accepted and this is a MVP issue to be fixed.

api/v1/joint-invoice POST

Sending Joint Invoice message data to Elering; context=class MarketParticipantContext {
marketParticipantIdentification: 38XJV-03000000-W
marketParticipantRole: GRID_OPERATOR
commodityType: ELECTRICITY
} headersList=[class JointInvoiceHeaders {
senderEic: 38XJV-03000000-W
receiverEic: 38XLATVENEK003-X
customerEic: 38X-AVP-OFLM00E7
commodityType: ELECTRICITY
meterEics: [38ZEE-00738295-3]
dataPeriodStart: 2024-09-30T00:00+03:00
dataPeriodEnd: 2024-09-30T00:00+03:00
fileName: 082098840613LATVENEK
}]

Basically the old avp accept the same day as a Period here is the example xml:
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<E_Invoice>
    <Header>
        <Date>2024-10-07</Date>
        <FileId>082098840613LATVENEK</FileId>
        <Version>1.2</Version>
    </Header>
    <Invoice sellerRegnumber="11050857" regNumber="48004100297" invoiceId="082098840613">
        <InvoiceParties>
            <SellerParty>
                <TransactionPartnerCode>012401</TransactionPartnerCode>
                <Name>Elektrilevi OÜ</Name>
                <RegNumber>11050857</RegNumber>
                <VATRegNumber>EE100366327</VATRegNumber>
            </SellerParty>
            <BuyerParty>
                <UniqueCode>38X-AVP-OFLM00E7</UniqueCode>
                <Name>Pärna, Piret</Name>
                <RegNumber>48004100297</RegNumber>
            </BuyerParty>
            <RecipientParty>
                <UniqueCode>38XLATVENEK003-X</UniqueCode>
                <Name>Elektrum Eesti OÜ</Name>
                <RegNumber>11399985</RegNumber>
            </RecipientParty>
        </InvoiceParties>
        <InvoiceInformation>
            <Type type="DEB"/>
            <DocumentName>Arve</DocumentName>
            <InvoiceNumber>082098840613</InvoiceNumber>
            <InvoiceDate>2024-09-30</InvoiceDate>
            <Period>
                <StartDate>2024-09-30</StartDate>
                <EndDate>2024-09-30</EndDate>
            </Period>
        </InvoiceInformation>
        <InvoiceSumGroup>
            <InvoiceSum>0.9900</InvoiceSum>
            <TotalSum>0.99</TotalSum>
            <Currency>EUR</Currency>
        </InvoiceSumGroup>
        <InvoiceItem>
            <InvoiceItemGroup groupId="7450827235">
                <ItemEntry>
                    <Description>Elektri edastamine: päev 0,0369€/kWh, kogus 8,525 kWh</Description>
                    <ItemReserve extensionId="ITEM_PRICE">
                        <InformationName>Ühiku maksumus (ilma maksudeta)</InformationName>
                        <InformationContent>0,0369</InformationContent>
                    </ItemReserve>
                    <ItemDetailInfo>
                        <ItemUnit>KWH</ItemUnit>
                        <ItemAmount>8.5250</ItemAmount>
                    </ItemDetailInfo>
                    <ItemSum>0.3100</ItemSum>
                    <VAT vatId="TAX">
                        <VATRate>22</VATRate>
                    </VAT>
                    <Period>
                        <StartDate>2024-09-30</StartDate>
                        <EndDate>2024-09-30</EndDate>
                    </Period>
                </ItemEntry>
                <ItemEntry>
                    <Description>Elektri edastamine: öö 0,021€/kWh, kogus 3,933 kWh</Description>
                    <ItemReserve extensionId="ITEM_PRICE">
                        <InformationName>Ühiku maksumus (ilma maksudeta)</InformationName>
                        <InformationContent>0,021</InformationContent>
                    </ItemReserve>
                    <ItemDetailInfo>
                        <ItemUnit>KWH</ItemUnit>
                        <ItemAmount>3.9330</ItemAmount>
                    </ItemDetailInfo>
                    <ItemSum>0.0800</ItemSum>
                    <VAT vatId="TAX">
                        <VATRate>22</VATRate>
                    </VAT>
                    <Period>
                        <StartDate>2024-09-30</StartDate>
                        <EndDate>2024-09-30</EndDate>
                    </Period>
                </ItemEntry>
                <ItemEntry>
                    <Description>Kuutasu, kuni 16A: 13,50€ kuus</Description>
                    <ItemReserve extensionId="ITEM_PRICE">
                        <InformationName>Ühiku maksumus (ilma maksudeta)</InformationName>
                        <InformationContent>13,50</InformationContent>
                    </ItemReserve>
                    <ItemDetailInfo>
                        <ItemAmount>0.0333</ItemAmount>
                    </ItemDetailInfo>
                    <ItemSum>0.4500</ItemSum>
                    <VAT vatId="TAX">
                        <VATRate>22</VATRate>
                    </VAT>
                    <Period>
                        <StartDate>2024-09-30</StartDate>
                        <EndDate>2024-09-30</EndDate>
                    </Period>
                </ItemEntry>
                <ItemEntry>
                    <Description>Taastuvenergia tasu 0,0105€/kWh, kogus 12,458 kWh</Description>
                    <ItemReserve extensionId="ITEM_PRICE">
                        <InformationName>Ühiku maksumus (ilma maksudeta)</InformationName>
                        <InformationContent>0,0105</InformationContent>
                    </ItemReserve>
                    <ItemDetailInfo>
                        <ItemUnit>KWH</ItemUnit>
                        <ItemAmount>12.4580</ItemAmount>
                    </ItemDetailInfo>
                    <ItemSum>0.1300</ItemSum>
                    <VAT vatId="TAX">
                        <VATRate>22</VATRate>
                    </VAT>
                    <Period>
                        <StartDate>2024-09-30</StartDate>
                        <EndDate>2024-09-30</EndDate>
                    </Period>
                </ItemEntry>
                <ItemEntry>
                    <Description>Elektriaktsiis 0,00145€/kWh, kogus 12,458 kWh</Description>
                    <ItemReserve extensionId="ITEM_PRICE">
                        <InformationName>Ühiku maksumus (ilma maksudeta)</InformationName>
                        <InformationContent>0,00145</InformationContent>
                    </ItemReserve>
                    <ItemDetailInfo>
                        <ItemUnit>KWH</ItemUnit>
                        <ItemAmount>12.4580</ItemAmount>
                    </ItemDetailInfo>
                    <ItemSum>0.0200</ItemSum>
                    <VAT vatId="TAX">
                        <VATRate>22</VATRate>
                    </VAT>
                    <Period>
                        <StartDate>2024-09-30</StartDate>
                        <EndDate>2024-09-30</EndDate>
                    </Period>
                </ItemEntry>
                <GroupEntry>
                    <GroupDescription>082365617209</GroupDescription>
                    <Extension extensionId="RATE_SCHEDULE_1">
                        <InformationName>Tariifipakett</InformationName>
                        <InformationContent>Võrk 4</InformationContent>
                    </Extension>
                    <Extension extensionId="MP_EIC_1">
                        <InformationName>Mõõtepunkt</InformationName>
                        <InformationContent>38ZEE-00738295-3</InformationContent>
                    </Extension>
                    <Extension extensionId="PREMISE_ADDRESS_1">
                        <InformationName>Tarbimiskoht</InformationName>
                        <InformationContent>eramaja, Linnumarja tänav 2, Alliku küla Saue vald Harju maakond</InformationContent>
                    </Extension>
                    <Extension extensionId="SERVICE_TYPE">
                        <InformationName>Teenuslepingu tüüp</InformationName>
                        <InformationContent>Network Service</InformationContent>
                    </Extension>
                    <Extension extensionId="RMTP_PER">
                        <InformationName>RMTP periood</InformationName>
                        <InformationContent>2024-09-30</InformationContent>
                    </Extension>
                    <Extension extensionId="BSEG_START_DATE">
                        <InformationName>Alguskuupäev</InformationName>
                        <InformationContent>2024-09-30</InformationContent>
                    </Extension>
                    <Extension extensionId="BSEG_END_DATE">
                        <InformationName>Lõppkuupäev</InformationName>
                        <InformationContent>2024-09-30</InformationContent>
                    </Extension>
                    <Extension extensionId="SERVICE_TYPE_ROLL">
                        <InformationName>Teenuslepingu tüübi eritunnus Usage tüübi lepingu eristamiseks</InformationName>
                        <InformationContent>BD</InformationContent>
                    </Extension>
                    <Extension extensionId="METER_NR_1_1">
                        <InformationName>Arvestinumber</InformationName>
                        <InformationContent>39074010</InformationContent>
                    </Extension>
                    <Extension extensionId="END_MR_DATE_1_1">
                        <InformationName>Lõppnäidu kuupäev</InformationName>
                        <InformationContent>2024-09-30-23.59.59</InformationContent>
                    </Extension>
                    <Extension extensionId="END_MR_A_24H_1_1">
                        <InformationName>Lõppnäit, Elekter</InformationName>
                        <InformationContent>37480.878</InformationContent>
                    </Extension>
                    <Extension extensionId="END_MR_RP_24H_1_1">
                        <InformationName>Lõppnäit, Reaktiivenergia võrku andmine</InformationName>
                        <InformationContent>0</InformationContent>
                    </Extension>
                    <Extension extensionId="END_MR_RC_24H_1_1">
                        <InformationName>Lõppnäit, Reaktiivenergia tarbimine</InformationName>
                        <InformationContent>0</InformationContent>
                    </Extension>
                    <Extension extensionId="USAGE_A_24H_1_1">
                        <InformationName>Tarbimine, Elekter (kWh)</InformationName>
                        <InformationContent>12.4580</InformationContent>
                    </Extension>
                    <Extension extensionId="USAGE_A_NIGHT22_1_1">
                        <InformationName>aktiivenergia öine kogus (kWh),uus ajatsoon, tarbimine koos tipuga</InformationName>
                        <InformationContent>3.9330</InformationContent>
                    </Extension>
                    <Extension extensionId="USAGE_A_WDPEAK_1_1">
                        <InformationName>aktiivenergia päevase tipuaja kogus (kWh)</InformationName>
                        <InformationContent>2.0460</InformationContent>
                    </Extension>
                    <Extension extensionId="USAGE_A_DAY22_1_1">
                        <InformationName>aktiivenergia päevane kogus (kWh), uus ajatsoon, tarbimine koos tipuga</InformationName>
                        <InformationContent>8.5250</InformationContent>
                    </Extension>
                    <Extension extensionId="USAGE_A_NOWDPEAK_1_1">
                        <InformationName>aktiivenergia öise, puhkepäevase tipuaja kogus (kWh)</InformationName>
                        <InformationContent>0.0000</InformationContent>
                    </Extension>
                    <Extension extensionId="FT_ID">
                        <InformationName>Finantstehing</InformationName>
                        <InformationContent>082606565722</InformationContent>
                    </Extension>
                    <GroupSum>0.9900</GroupSum>
                </GroupEntry>
            </InvoiceItemGroup>
        </InvoiceItem>
        <AdditionalInformation>
            <InformationContent>Elektrilevi OÜ teatab:</InformationContent>
        </AdditionalInformation>
        <AdditionalInformation>
            <InformationContent>1. oktoobrist 2024 muutusid Elektrilevi võrguteenuse hinnad: https://elektrilevi.ee/et/vorguleping/vorgutasu-muudatus</InformationContent>
        </AdditionalInformation>
        <AdditionalInformation>
            <InformationContent>1. oktoobrist 2024 muutusid ka võrgulepingu tüüptingimused, millega on võimalik tutvuda Elektrilevi veebilehel https://elektrilevi.ee/et/tingimused</InformationContent>
        </AdditionalInformation>
        <PaymentInfo>
            <Currency>EUR</Currency>
            <PaymentDescription>NULL</PaymentDescription>
            <Payable>NO</Payable>
            <PaymentTotalSum>0</PaymentTotalSum>
            <PayerName>NULL</PayerName>
            <PaymentId>NULL</PaymentId>
            <PayToAccount>0</PayToAccount>
            <PayToName>NULL</PayToName>
        </PaymentInfo>
    </Invoice>
    <Footer>
        <TotalNumberInvoices>1</TotalNumberInvoices>
        <TotalAmount>0.00</TotalAmount>
    </Footer>
</E_Invoice> `

**Comment by EinarArro** [comment]
Comment from Mari-Liis  Alaküla: okay, now i understand. we will refactor hpw we send out the joint invoices, you can close the issue we reported
