### ISSUE TITLE
Joint invoice, single XML for multiple metering points - MVP critical functionality

### ISSUE THREAD

**Issue by andrepost** [Elering/estfeed-datahub-docs#108]
Currently Estfeed Invoice API is expecting the number of XML files equal to the metering point EICs in header. Problem is that Estonian Invoice XML is generated once per multiple EICs. Which means that single invoice XML will contain all the EICs data.

Would like to remove the need for multiple XML files for multiple metering points.

**Comment by EinarArro** [comment]
Check the updated documentation and examples in https://github.com/Elering/estfeed-datahub-docs/blob/main/eng/14-joint-invoice.md
Does this answer your question?
