### ISSUE TITLE
[EDH-3545] - Agreement editor role alone doesn't allow to create new SUPPLY agreements

### ISSUE THREAD

**Issue by EinarArro** [Elering/estfeed-datahub-docs#123]
# *Problem*

VIEW_CUSTOMER acces right is not associated with OPEN_SUPPLIER EDITOR_AGREEMENT role.
Therefore if you try to add new SUPPLY agreement via UI with EDITOR_AGREEMENT user role, then you get an error:

![CleanShot 2024-11-22 at 16 01 02@2x](https://github.com/user-attachments/assets/b1269926-9d71-4483-a99e-1c28a689dcad)

*Steps to reproduce*
 * _Remove ADMIN role from user OPEN_SUPPLIER user_
 * _Add EDITOR_AGREEMENT to user_
 * _Open OPP UI and start to add new agreement_
 * _Push button "Search customer"_
 * _Fill up the fields (like EIC) and push "Search"_

# _*Expected result*_

_User can search for Customer_
# *Actual Result*

_User cannot search, because VIEW_CUSTOMER is not associated with EDITOR_AGREEMENT role: [https://confluence.elering.sise/display/EAL/Roles+and+Rights]_

# *Impact (If known)*

_Users without ADMIN role cannot add new SUPPLY agreements_

# _Work-a-round_

_Assing ADMIN role to user_

**Comment by kristjanZ** [comment]
Fixed in Release 0.23.17.
Editor Agreement role for open supplier now also grants customer search privilege.
Also in order to be able register the agreement the user also needs to have Viewer Metering Point role

**Comment by kristjanZ** [comment]
As of Release 0.23.19 adding of the Viewer Metering Point role additionally for Editor Agreement role is no longer required
