### ISSUE TITLE
[EDH-3544] customer-authorization/search doesn't work

### ISSUE THREAD

**Issue by ErkkiGit** [Elering/estfeed-datahub-docs#125]
**Problem**
Bug found in live. Every time when request has been made, then "Permission not found" is in response.

 

**Steps to reproduce**

Tested in DEV.

User: 38708270238

Role: Some open supplier ; 38XVK-08600000-Q; Open Supplier

Agreements -> Access permissions -> Search

POST https://dev-datahub.elering.ee/api/v1/customer-authorization/search

```
{
    "marketParticipantContext": {
        "marketParticipantIdentification": "38XVK-08600000-Q",
        "marketParticipantRole": "OPEN_SUPPLIER",
        "commodityType": "ELECTRICITY"
    },
    "periodStart": "2024-11-22T15:58:13.873+02:00",
    "periodEnd": "2024-11-22T15:58:13.873+02:00"
}
```
**Expected result**
Allowed customers and metering points are in the response

**Actual Result**
```
{
    "id": "764c5303-344e-45b0-90ac-0d6396fbbe17",
    "cause": {
        "message": "Permission not found",
        "code": "opp.error.business.not-found.permission",
        "queue": "parm_find_permissions_by_mandate_id_req_q",
        "traceId": "05c596f68ee24fd3a899e4e28c14d097"
    }
}
```
![image](https://github.com/user-attachments/assets/c066ee64-1850-4bb0-b86d-da852c916ba9)

**Comment by kristjanZ** [comment]
Fixed in Release 0.23.16
