### ISSUE TITLE
[EDH-3575] - Agreement DELETE throws error, but delete is actually performed

### ISSUE THREAD

**Issue by EinarArro** [Elering/estfeed-datahub-docs#128]
## Problem

OS tried to delete a SUPPLY agreement. Got technical error "agreement not found" as response, but after checking the database, the delete was actually performed

## Steps to reproduce

The steps are hard to identify. Kristjan had a guess, that the Infinispan cache could be the reason, but reality is, that nobody knows the exact pattern

## Expected result

No errors, if the action was performed

## Additional information

_hidden, because Live data_

**Comment by kristjanZ** [comment]
fixed in Release 0.23.27
