### ISSUE TITLE
[EDH-3686] - SUPPLY.validFrom can be more than 48h in the past

### ISSUE THREAD

**Issue by EinarArro** [Elering/estfeed-datahub-docs#147]
## Problem

By the business rules, the "validFrom" of the SUPPLY agreement can be up to 48h in the past if it matches the "validFrom" of the GRID agreement. At the moment the System allows to add SUPPLY agreement with past "validFrom" value, that is more than 48h in the past.

## Steps to reproduce

* Create new or use existing Metering Point
* Create GRID agreement with more than 48h but less than 72h in the past:

```json
{
  "marketParticipantContext": {
    "marketParticipantIdentification": "38X-EIN-GO-----0",
    "marketParticipantRole": "GRID_OPERATOR",
    "commodityType": "ELECTRICITY"
  },
  "agreement": {
    "agreementType": "GRID",
    "commodityType": "ELECTRICITY",
    "serviceProviderEic": "38X-EIN-GO-----0",
    "customerEic": "38X-AVP-ZW6700C6",
    "validFrom": "2024-12-07T00:00:00+02:00",
    "agreementId": "einar-2024-12-09T13:57:23.308286+02:00-EST",
    "meterEic": "38ZGO-1000009B-1"
  }
}
```

* Try to create SUPPLY agreement with the same dates

## Expected result

System rejects the request and provides earliest allowed datetime as "2024-12-08T00:00:00+02:00", because:

* 2024-12-09T13:57:25+02:00 - 48h = 2024-12-07T13:57:25+02:00
* As the validFrom has to be 00:00 Estonian time, then the next allowed validFrom slot is 2024-12-08T00:00:00+02:00

## Actual Result

System allows to add SUPPLY agreement more than 48h in the past:

```json
{
  "marketParticipantContext": {
    "marketParticipantIdentification": "38X-EIN-OS-----J",
    "marketParticipantRole": "OPEN_SUPPLIER",
    "commodityType": "ELECTRICITY"
  },
  "agreement": {
    "agreementType": "SUPPLY",
    "commodityType": "ELECTRICITY",
    "serviceProviderEic": "38X-EIN-OS-----J",
    "customerEic": "38X-AVP-ZW6700C6",
    "validFrom": "2024-12-07T00:00:00+02:00",
    "agreementId": "einar-2024-12-09T13:57:23.308286+02:00-EST",
    "meterEic": "38ZGO-1000009B-1"
  }
}
```

## Impact (If known)

Wrong business rule allowed

## Work-a-round

None

**Comment by kristjanZ** [comment]
Fixed in Release 0.23.43
