### ISSUE TITLE
[EDH-3713] "Metering point not found in cache"/"Agreement not found" error in new agreement flow

### ISSUE THREAD

**Issue by mailimarkvardt** [Elering/estfeed-datahub-docs#150]
**Problem**
If customer has NATURAL GAS agreements, then searching it's metering points in new agreement flow ends in error "metering point not found in cache" and agreement cannot be concluded. 

**Steps to reproduce**
1. Logged in as OS, go to Agreements - New agreement
2. Add customer EIC and press Metering points button, observe the result

**Expected result**
Customer's metering points (only electricity commodity type) are returned
**Actual result**
"Metering point not found in cache" or "Agreement not found" error message

**Comment by kristjanZ** [comment]
Fixed in Release 0.23.45
