### ISSUE TITLE
[EDH-3599] The PP of the owner of the MP should not get access to MD or it's DD

### ISSUE THREAD

**Issue by mailimarkvardt** [Elering/estfeed-datahub-docs#152]
**Problem**
At the moment, when metering data is sent to Estfeed, data distributions are sent to metering point owner's PP (all upper levels if several).
This should not happen, metering data should not be sent in DD nor grant access by metering data query for MP's PP. 

Steps to reproduce
1. Metering data is uploaded to Estfeed by GO
2. Check DD with type "METERING_DATA" as GO's portfolio provider. Observe that metering data DD is available.

Expected result
DD is not sent to any of the MP owner's PP. 

Actual result
All MP owner's PP get DD about metering data.

**Comment by kristjanZ** [comment]
Fixed with Release 0.23.44
