### ISSUE TITLE
[EDH-3742] Previous SUPPLY should not be restored when new SUPPLY is deleted

### ISSUE THREAD

**Issue by elinasirk** [Elering/estfeed-datahub-docs#154]
### Problem
In case initial SUPPLY agreement is terminated because a new SUPPLY agreement is registered and after that deleted (cancelled), then the initial SUPPY agreement is restored, but shouldn't be.

### Steps to reproduce

Add initial SUPPLY agreement
Add new SUPPLY agreement
Cancel/delete new SUPPLY agreement
### Expected result
New SUPPLY agreement is cancelled (relevant DDs created). No further actions.

### Actual Result
New SUPPLY agreement is cancelled (relevant DDs created). Initial SUPPLY agreement is restored.

### Impact (If known)
Supplier is confured regarding the restored agreement and may not realise the initial agreement is still valid according to Datahub.

### Workaround
Initial supplier terminated it's agreement, but this option may not be available when the suppler discovers the restoration of the agreement.

**Comment by egertmitt** [comment]
Fixed with the release 1.0.2 https://github.com/Elering/estfeed-datahub-docs/blob/main/CHANGELOG.md#edh-3772-release-102
