### ISSUE TITLE
[EDH-2427] Cannot update GRID agreement's validTo to less than SUPPLY agreement's validFrom

### ISSUE THREAD

**Issue by EinarArro** [Elering/estfeed-datahub-docs#21]
# Steps

-  Create GRID agreement, where: 
  - validFrom is today or tomorrow
  - validTo is NULL
- Create SUPPLY agreement where:
  - validFrom is somewhere in the future (like in 30 days)
  - validTo is whatever you want
- Try to update the GRID agreement the way, that new validTo date is less than validFrom of the SUPPLY agreement
- Expected result:
  - SUPPLY agreement get's deleted (because it cannot ever activate)
  - SUPPLY agreement change is distributed to OS
  - DD message contains deletedTime and deletedBy
- Actual result - error message:

```json
  {
    "id": "3e95eb5d-2e28-49ae-977e-f3ba997fb168",
    "cause": {
      "message": "Grid agreement must exist on the whole period of supply agreement",
      "code": "mpm.error.business.grid-agreement-is-prerequisite-of-supply-agreement",
      "queue": "mpm_update_agreement_req_q",
      "traceId": "0f4997e97388457987c056a656b8406c",
      "args": []
    }
  }
```

# Additional information
- if the SUPLLY agreement get's deleted and the GRID agreement gets extended again, then the SUPPLY agreement should not be reactivated automatically
- Also Kajali and Marko requested, that the /agreement/search API should contain deletedTime and deletedBy information

**Comment by mailimarkvardt** [comment]
Grid agreement can now have ValidTo before ValidFrom of Supply agreement. Supply agreement is deleted in this case and DD messages sent, including DELETE_BC_GRID_UPDATE to supplier.
