### ISSUE TITLE
[EDH-2294] [EDH-2533] Client Portal creates a Customer to Datahub without EIC code

### ISSUE THREAD

**Issue by elinasirk** [Elering/estfeed-datahub-docs#24]
### Steps

1. Log in to Public Test Customer Portal for the first time
2. Log in to Public test Datahub for the first time
3. Try to add Customer with the personal ID that was used to log in to Customer Portal
4. Result: Get an error. Because logging in to Customer Portal created a Customer without EIC code to Datahub.

**Comment by EinarArro** [comment]
Will be fixed with EDH-2533
