### ISSUE TITLE
[EDH-2478] Metering data not updated via import

### ISSUE THREAD

**Issue by EinarArro** [Elering/estfeed-datahub-docs#33]
# Steps
* Create metering data (doesn't matter how)
* Search for metering data in the OPP UI
* Export
* Modify values
* Import
* Verify, that import job was successful on "Metering Data Status" page
* Search for metering data again in the UI
* Expected result - metering data is updated
* Actual result - shows old data

**Comment by mailimarkvardt** [comment]
Metering data can now be updated by re-importing.
