### ISSUE TITLE
[EDH-2538] - Wrong DD message for OS about GS agreement

### ISSUE THREAD

**Issue by EinarArro** [Elering/estfeed-datahub-docs#35]
# Summary
OS, who just created an OS agreement gets DD message about GS agreement (that was deleted)

# Steps
* Create new MP
* Create GRID agreement
* Check, that system will created GS agreement
* Create SUPPLY agreement with same validity dates as GRID agreement
* Check, agreements of MP and verify, that GS agreement got deleted - OK:
![CleanShot 2024-06-03 at 18 15 57@2x](https://github.com/Elering/estfeed-datahub-docs/assets/2980916/d8c3b980-7bac-4982-9ba3-b9ba6309ae75)
* Check DD-s
* Expected result - OS, who created the SUPPLY agreement gets no DD messages
* Actual result - OS gets DD message about GS agreement:
  * Request:
```json
{
  "marketParticipantContext": {
    "marketParticipantIdentification": "38X-EIN-ALL----B",
    "marketParticipantRole": "OPEN_SUPPLIER",
    "commodityType": "ELECTRICITY"
  },
  "dataDistributionAttributes": {
    "createdTimeFrom": "2024-06-03T17:57:17.891437+03:00",
    "createdTimeTo": "2024-06-03T18:02:17.891466+03:00",
    "resourceType": "AGREEMENT"
  },
  "pagination": {
    "page": 0,
    "pageSize": 1000000
  }
}
```
  * Response:
```json
{
  "dataDistributions": [
    {
      "id": 4816,
      "createdTime": "2024-06-03T14:58:24.417761500Z",
      "resourceType": "AGREEMENT",
      "content": "[{\"meterEic\":\"38ZGO-10000024-D\",\"agreementType\":\"GENERAL_SERVICE\",\"preliminaryTerminationFee\":false,\"commodityType\":\"ELECTRICITY\",\"validFrom\":\"2024-06-02T21:00Z\"}]"
    }
  ],
  "pagination": {
    "page": 0,
    "totalPages": 1
  }
}
```

**Comment by villisco** [comment]
Fixed in release 0.9.0:
https://github.com/Elering/estfeed-datahub-docs/blob/main/CHANGELOG.md#edh-2721-release-090
