### ISSUE TITLE
[EDH-2826] - Imperfect metering data excels not imported

### ISSUE THREAD

**Issue by elinasirk** [Elering/estfeed-datahub-docs#44]
### Problem

In some cases where the metering data excel has imperfect sheet, the whole file is not imported.

- The first sheet is correct but second sheet is empty - metering data from the first sheet is not imported, gives unsupported file format error
- First sheet is empty, metering data is on the second sheet - metering data from the second sheet is not imported, gives unsupported file format error

### Steps to reproduce

1. Import a file that has some mistake
2. See that the data was not imported

### Expected result

Correct sheets from the file should be imported.

### Actual Result

Data is not imported, error message was shown

**Comment by kristjanZ** [comment]
Fixed in  Release 0.23.40
