### ISSUE TITLE
[EDH-2951] - Wrong METERING_DATA DD messages to Eesti Gaas

### ISSUE THREAD

**Issue by EinarArro** [Elering/estfeed-datahub-docs#50]
# Problem

Eesti Gaas receives a lot of METERING_DATA DD messages about Metering Points, where they have no relation.

# Steps to reproduce
Check the DD messages as Eesti Gaas (EIC = '38X-AVP-9VD000EP')

# Expected result
Market Participants receive DD METERING_DATA messages only about those MP-s, where they have some needed relation

# Impact (If known)
Lots of DD messages, that the systems of Market Participants cannot handle, as the MP doesn't exist in their system

# Work-a-round
None

**Comment by villisco** [comment]
Deployed with latest release 0.13.0:
https://github.com/Elering/estfeed-datahub-docs/blob/main/CHANGELOG.md#edh-3012-release-0130

Closing issue.
