### ISSUE TITLE
[EDH-2909] [EDH-2852] Future agreements: Metering point cannot be found using Customer EIC and Customer EIC not displayed in MP list

### ISSUE THREAD

**Issue by mailimarkvardt** [Elering/estfeed-datahub-docs#69]
**Problem**
When metering point has future agreement (validFrom in the future), this metering point cannot be found in Metering Point search using Customer EIC.

**Steps to reproduce** 

1. Create a grid agreement with ValidFrom in the future by some GO 
2. Go to Metering points - search by Customer EIC

**Expected result:** 
Metering point is found. 
**Actual result:** 
Metering point not found.

**Workaround:** 
Searching using MP eic in Metering point's EIC works correctly, also in Agreement search agreement is found by Customer EIC and MP EIC.

**Comment by ErkkiGit** [comment]
https://jira.elering.sise/browse/EDH-2909
