### ISSUE TITLE
[EDH-3155] - Balance Provider 2 report is generated for all Open Suppliers

### ISSUE THREAD

**Issue by elinasirk** [Elering/estfeed-datahub-docs#77]
Balance Provider 2 report needs to be generated for service providers who Elering has portfolio agreement (the service provider needs to be the customer). However this is not counted.

Balance Provider 2 report is generated for all Open Suppliers. However the report for the incorrect service providers is empty.

**Comment by kristjanZ** [comment]
https://github.com/Elering/estfeed-datahub-docs/blob/main/CHANGELOG.md
Release 0.23.0

**Comment by ErkkiGit** [comment]
https://jira.elering.sise/browse/EDH-3155
