### ISSUE TITLE
Empty dataset is returned for shared MP

### ISSUE THREAD

**Issue by D-m-i-t-r-i-K** [Elering/estfeed-datahub-docs#82]
When querying shared MP data using OS role and "legalConsent=true" an empty dataset is returned.

**Endpoint:** /api/v1/meter-data/search

**Request:**
{
   "marketParticipantContext": {
      "marketParticipantIdentification": "CORRECT-X-EIC-HERE",
      "marketParticipantRole": "OPEN_SUPPLIER",
      "commodityType": "ELECTRICITY"
  },
   "meterEic": "CORRECT-Z-EIC-HERE",
      "periodStart": "2024-10-01T00:00:00Z",
      "legalConsent": true,
      "pagination": {
         "page": 0,
         "pageSize": 500
      }
}

**Response:**
{
   "meterEic": "CORRECT-Z-EIC-HERE",
   "commodityType": "ELECTRICITY",
   "periods": [],
   "pagination": {
      "page": 0,
      "totalPages": 0
   }
}

**Comment by EinarArro** [comment]
What does the "shared MP" mean?
Can you give me an EIC code of such MP?

**Comment by D-m-i-t-r-i-K** [comment]
Hi! Maybe it is not correct terminology, but under "shared MP" i mean metering points which were shared to us by TSO/DSO via agreements, or otherwords, metering points which data we can request as a client. Yesterday we have discussed this problem with Elina, and, as i understood, this problem exists on public-test environment, but in your internal test environment this issue already fixed. Due to GoLive-Test will use newer environment compared to public-test, hopefully the issue will be fixed there as well. We have agreed with Elina, that if problem still persist in GoLive-Test, then it will be registered as a bug. So during GoLive-Test we will check it (of course it depends also on TSO/DSO, who need to load measured data to Datahub).

**Comment by D-m-i-t-r-i-K** [comment]
Problem was resolved in GoLive-Test release.
