### ISSUE TITLE
[EDH-3314] GS agreements with future dates are distributed

### ISSUE THREAD

**Issue by DenEnefit** [Elering/estfeed-datahub-docs#85]
**Describe the bug**
It was said that General Supply agreements will not be distributed ahead of their validity period. Yet still, people managed to receive from data-distribution end-point a GS agreement with validFrom of 11.10.2024 on the 10th of October.

**To Reproduce**
1. Have data that matches the description
2. Query DD endpoint
3. Check the validFrom

**Expected behavior**
Distribute GS agreements when validFrom matches today's date.

**Screenshots**
Screenshot made on 10.10.2024
![image](https://github.com/user-attachments/assets/b7bf33c5-a952-4fbe-8bf3-9b390e925af7)

**Comment by egertmitt** [comment]
@EinarArro  - can you register this issue in internal Jira?

**Comment by EinarArro** [comment]
Seems to be fixed.
