### ISSUE TITLE
[EDH-3317] /api/v1/meter/search/customer is slow (20+ s) when customer has more than 100 metering points

### ISSUE THREAD

**Issue by mailimarkvardt** [Elering/estfeed-datahub-docs#94]
**Problem:** When using /api/v1/meter/search/customer with customer's EIC that has 100 or more metering points, search is very slow - 20-40 seconds. 

**impact:** OS has customer waiting during sales process, This query will then be followed by querying the related agreements .

**Comment by kristjanZ** [comment]
some improvements were made. should be less than 10 seconds now
