### ISSUE TITLE
Joint-invoice format doesnt match the initial specification

### ISSUE THREAD

**Issue by solodovnikovae** [Elering/estfeed-datahub-docs#98]
Based on the initial specification: https://github.com/Elering/estfeed-datahub-docs/blob/main/eng/14-joint-invoice.md#introduction
should be sent in **base64** format, which is used for Estonian E-arve, instead atm the messages are being send in **AVP ForwardInvoice XML** 
![joint_invoice_14102024](https://github.com/user-attachments/assets/578ed8bb-7414-44cb-8bf3-c4ef794b3835)
For this reason we are unable to receive joint-invoice data.

**Comment by EinarArro** [comment]
Elektrilevi changed its implementation. Now the "download" returns base64 string, that contains only the e-invoice XML
